const LOGIN = 'login';
const HOME = 'home';
const GET_CATEGORIES = 'categories';
const FAVOURITES = 'favorites';
const REGISTER = 'register';
const PROFILE = 'profile';
const UPDATE_PROFILE = 'update-profile';
const CARTS = 'carts';
String? token='';
bool? isArabic =false;
String language = isArabic== true? 'ar':'en';
bool? isDark = false;